### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by emmalish** [lssinc/voyage-app-angular-ecommerce#23]
As a user, I want to know more about the company that built the app.

1. User taps on hamburger menu
2. User taps on ABOUT LIGHTHOUSE
3. The page displays information on the company. Marketing copy is below:

We do legacy (support and modernization).

- 18 Years of enterprise experience
- 450+ Modernization projects

Think asset. Not Liability.
The greatest challenges in IT are operational, not technological.
By its very definition legacy software serves a valuable purpose. It's an asset. An aging one, to be sure, but not one to treat with a cavalier “rip and replace” approach. That’s because, for most organizations, the greatest challenges are operational, not technological. Designing the right business processes and aligning resources, both human and technology, are critical for a successful modernization effort.

4. There is a Learn Some Mo' button which takes users to the Lighthouse marketing site.

See high-fidelity prototype for UI requirements:
https://preview.uxpin.com/aec6c08d927ec6d8f1c1d054a0031f3991696cd1#/pages/114346070

**Comment by raymer** [comment]
Done
